#!/bin/sh
# Block editing .lua files in cfg/nvim/ (they're auto-generated by nfnl from Fennel)
jq -c 'if (.tool_input.file_path | test(".*cfg/nvim/.*\\.lua$")) then {decision: "block", reason: "Cannot edit .lua files in cfg/nvim/ - they are auto-generated by nfnl from Fennel source. Edit the corresponding .fnl file instead."} else {decision: "approve"} end'
