debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

[retry]

[docker]
entrypoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false

[api]
entrypoint = "traefik"
dashboard = true
