#!/bin/sh
echo "JUPYTER-CLJ Starting"

# Setting the java version to 8
export PATH=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:$PATH

notebook_dir=~/prog/notebook/
cd $notebook_dir
exec 2>&1

echo "Installing Kernel"
lein jupyter install-kernel

echo "Starting notebook"
export LEIN_WORKING_DIRECTORY=$notebook_dir
exec jupyter notebook --no-browser

echo "Notebook exited"
