version: '3'

services:
  proxy:
    image: traefik
    container_name: traefik-proxy
    volumes:
      - ./nginx/config:/config
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
    labels:
      - "traefik.docker.network=local"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.localhost"
      - "traefik.port=8080"
      - "traefik.protocol=http"

  portainer:
    image: portainer/portainer
    container_name: portainer
    depends_on:
      - proxy
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.docker.network=local"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:portainer.localhost"
      - "traefik.port=9000"
      - "traefik.protocol=http"

  watchtower:
    image: v2tec/watchtower
    container_name: services-watchtower
    command: --cleanup traefik-proxy portainer services-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:

networks:
  proxy:
    external: true
